
previews:
  generation: automatic

services:
  # Main MERN Stack Application
  - type: web
    runtime: docker
    name: example-react-app
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    numInstances: 1
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: echo "Building with Docker..."
    startCommand: bun run --cwd server-ts start
    disk:
      name: sqlite-data
      mountPath: /app/server-ts/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: IS_SSR
        value: "true"
      - key: DATABASE_TYPE
        value: sqlite
      - key: SQLITE_DATABASE_PATH
        value: ./server-ts/data/database.sqlite
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - fromGroup: app-config

# No external database needed - using SQLite file-based database

envVarGroups:
  - name: app-config
    envVars:
      - key: VITE_API_BASE_URL
        value: https://example-react-app.onrender.com/api
      - key: VITE_WS_URL
        value: https://example-react-app.onrender.com
      - key: VITE_APP_NAME
        value: "React Todo & Chat App 2025"
      - key: VITE_APP_VERSION
        value: "1.0.0"
      - key: VITE_ENABLE_CHAT
        value: "true"
      - key: VITE_ENABLE_NOTIFICATIONS
        value: "true"
      - key: VITE_ENABLE_DARK_MODE
        value: "true"
      - key: CORS_ALLOW_ORIGINS
        value: https://example-react-app.onrender.com
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_FROM
        value: noreply@example-react-app.onrender.com